// Generated by gencpp from file node_communicate/infoRequest.msg
// DO NOT EDIT!


#ifndef NODE_COMMUNICATE_MESSAGE_INFOREQUEST_H
#define NODE_COMMUNICATE_MESSAGE_INFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_communicate
{
template <class ContainerAllocator>
struct infoRequest_
{
  typedef infoRequest_<ContainerAllocator> Type;

  infoRequest_()
    : request()  {
    }
  infoRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::node_communicate::infoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_communicate::infoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct infoRequest_

typedef ::node_communicate::infoRequest_<std::allocator<void> > infoRequest;

typedef boost::shared_ptr< ::node_communicate::infoRequest > infoRequestPtr;
typedef boost::shared_ptr< ::node_communicate::infoRequest const> infoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_communicate::infoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_communicate::infoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::node_communicate::infoRequest_<ContainerAllocator1> & lhs, const ::node_communicate::infoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::node_communicate::infoRequest_<ContainerAllocator1> & lhs, const ::node_communicate::infoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace node_communicate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::node_communicate::infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_communicate::infoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_communicate::infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_communicate::infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_communicate::infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_communicate::infoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_communicate::infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::node_communicate::infoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_communicate::infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_communicate/infoRequest";
  }

  static const char* value(const ::node_communicate::infoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_communicate::infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
;
  }

  static const char* value(const ::node_communicate::infoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_communicate::infoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct infoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_communicate::infoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_communicate::infoRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_COMMUNICATE_MESSAGE_INFOREQUEST_H
