// Generated by gencpp from file node_communicate/message.msg
// DO NOT EDIT!


#ifndef NODE_COMMUNICATE_MESSAGE_MESSAGE_H
#define NODE_COMMUNICATE_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_communicate
{
template <class ContainerAllocator>
struct message_
{
  typedef message_<ContainerAllocator> Type;

  message_()
    : info()  {
    }
  message_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::node_communicate::message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_communicate::message_<ContainerAllocator> const> ConstPtr;

}; // struct message_

typedef ::node_communicate::message_<std::allocator<void> > message;

typedef boost::shared_ptr< ::node_communicate::message > messagePtr;
typedef boost::shared_ptr< ::node_communicate::message const> messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_communicate::message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_communicate::message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::node_communicate::message_<ContainerAllocator1> & lhs, const ::node_communicate::message_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::node_communicate::message_<ContainerAllocator1> & lhs, const ::node_communicate::message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace node_communicate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::node_communicate::message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_communicate::message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_communicate::message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_communicate::message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_communicate::message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_communicate::message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_communicate::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::node_communicate::message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_communicate::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_communicate/message";
  }

  static const char* value(const ::node_communicate::message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_communicate::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string info\n"
;
  }

  static const char* value(const ::node_communicate::message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_communicate::message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_communicate::message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_communicate::message_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_COMMUNICATE_MESSAGE_MESSAGE_H
